# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: Environments
    type: string
    default: QA
    values:
      - QA
      - DEV
      - UAT

  - name: AllTests
    displayName: Run All Tests?
    type: boolean
    default: false
      

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
    checkLatest: true

- script: echo "start" # always runs
- ${{ if eq(parameters.AllTests, true) }}:
  - script: echo "this is a test" # runs when Boolran=true

- script: |
    npm ci    
  displayName: 'npm install'
- script: npx playwright install --with-deps chromium
  displayName: 'Install Playwright browsers'
- script: |
    npx playwright test --project=chromium    
  displayName: 'Run Tests'
  env:
    CI: 'true'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    searchFolder: 'test-results'
    testResultsFormat: 'JUnit'
    testResultsFiles: 'e2e-junit-results.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'My End-To-End Tests'
  condition: succeededOrFailed()
- task: PublishPipelineArtifact@1
  inputs:
    artifact: playwright-report-test
    publishLocation: 'pipeline'
  condition: succeededOrFailed()


