name: $(System.PullRequest.SourceBranch)_$(System.PullRequest.SourceCommitId)

trigger:
  - none

pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  - group: ENV_VARIABLES

parameters:
- name: Environments
  type: string
  default: prod
  values:
    - qa
    - dev
    - uat
    - prod

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: npm ci
    displayName: "npm install and build"

  - script: npx playwright install chromium --with-deps
    displayName: "Install Playwright Browser and Deps"

  - script: |
      echo "##vso[task.setvariable variable=ENV]${{ parameters.Environments }}"
      echo "##vso[task.setvariable variable=VALID_USERNAME]$(valid_username_saucedemo)"
      echo "##vso[task.setvariable variable=VALID_PASSWORD]$(valid_password_saucedemo)"
      echo "##vso[task.setvariable variable=INVALID_USERNAME]$(invalid_username_saucedemo)"
      echo "##vso[task.setvariable variable=INVALID_PASSWORD]$(invalid_password_saucedemo)"
    displayName: Set Variables

  - script: npx playwright test --project=chromium
    displayName: "Run All Tests"

  - task: PublishTestResults@2
    displayName: "Publish test results tab"
    inputs:
      searchFolder: "test-results"
      testResultsFormat: "JUnit"
      testResultsFiles: "e2e-junit-results.xml"
      testRunTitle: "My End-To-End Tests"
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(System.DefaultWorkingDirectory)/playwright-report"
      artifact: "Test Results"
      publishLocation: "pipeline"
    condition: succeededOrFailed()
