name: Azure Integration

on: 
  pull_request: 
    branches: 
      - master

jobs:
  Run-Azure-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Call Azure Pipeline
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/murillolopesoliveiraa/Azure%20Learning'
          azure-pipeline-name: 'Azure Integration'
          azure-devops-token: '${{ secrets.Azure_Token }}'
