name: Azure Integration

on: 
  pull_request: 
    branches: 
      - master

jobs:
  Run-Azure-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Call Azure Pipeline
        uses: Azure/pipelines@1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/murillolopesoliveiraa/Azure%20Learning'
          azure-pipeline-name: 'Playwright - All Tests'
          azure-devops-token: '7oxybdvnd4l6kvgdg3u7hrbm3oe6fzynug7sag3hwvwiheucv2ga'
