name: GitHub Actions Learning - Udemy
on: 
    workflow_dispatch:
    push: 
        branches: learning-GHA
jobs:
    Show-Comments:
        runs-on: ubuntu-latest
        steps:
            - name: Executing my script
              run: echo "Hello Murillo"
            - name: Getting GitHub context
              run: |
                echo "${{github.repository_owner}}"
                echo "${{github.repository}}"
