name: Matrix Example
on:
    workflow_dispatch:
    push: 
        branches: learning-GHA
jobs:
    build:
        # posso usar 'continue-on-error' se eu quiser q o build não pare qnd um dos jobs falharem
        #continue-on-error: true
        strategy:
            matrix:    # serve para rodar o build em todas as configurações possíveis abaixo. Exemplo: ubuntu com node 12, com node 14 etc. Windows com node 12, 14 etc
                node-version: [12, 14]
                os: [ubuntu-latest, windows-latest]
                include:
                  - node-version: 18   #posso adicionar uma combinação específica
                    os: ubuntu-latest
                exclude:
                  - node-version: 12   #posso excluir uma combinação específica
                    os: ubuntu-latest
        
        runs-on: ${{matrix.os}}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Node Version
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
            - name: Show variables
              run: |
                echo ${{matrix.node-version}}
                echo ${{matrix.os}}
    # Reusando um worflow
    deploy:
        needs: build
        uses: ./.github/workflows/reusable.yml  #a output 'result' vem desse workflow aqui e passa para o job 'deploy'
        with:
          myName: 'Murillo Lopes de Oliveira'
        secrets: 
            password: ${{secrets.INVALID_PASSWORD}}
    show-output:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
          - name: Print Output
            run: echo "${{needs.deploy.outputs.result}}" 
            # vou acessar a output do job 'Deploy', o qual está chamando o workflow 'reusable' e esse workflow tem uma output chamada 'result'


            