name: Matrix Example
on:
    pull_request: 
        branches: learning-GHA
jobs:
    build:
        # posso usar 'continue-on-error' se eu quiser q o build não pare qnd um dos jobs falharem
        #continue-on-error: true
        strategy:
            matrix:    # serve para rodar o build em todas as configurações possíveis abaixo. Exemplo: ubuntu com node 12, com node 14 etc. Windows com node 12, 14 etc
                node-version: [12, 14, 16]
                os: [ubuntu-latest, windows-latest]
        
        runs-on: ${{matrix.os}}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Node Version
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
            - name: Show variables
              run: |
                echo ${{matrix.node-version}}
                echo ${{matrix.os}}
        