name: Reusable Workflow
on:
    workflow_call:  #Preciso usar essa syntax para poder chamar esse workflow em outros workflows
        inputs:
            myName:
                description: Getting my name as a parameter
                type: string
        secrets:
            password:
                description: Getting my password
        outputs:
            result:
                description: The Job Result
                value: ${{jobs.Build.outputs.outcome}}
          
jobs:
  Build:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}  #esse job vai retornar a saída da linha 29
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
            echo "I'm Testing it"
            echo ${{inputs.myName}}
            echo "My password is ${{secrets.password}}"
      - name: Set Result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT