name: Playwright Pipeline (Smoke Tests)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    environment: 
      name: Prod
    env:
      ENV: prod
      VALID_USERNAME: ${{secrets.VALID_USERNAME}}
      VALID_PASSWORD: ${{secrets.VALID_PASSWORD}}
      INVALID_USERNAME: wrong_username
      INVALID_PASSWORD: ASDFGH
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 16.2.0
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright Tests 
      run: npx playwright test --grep=@Smoke --project=chromium
    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  Deploy:
    needs: Run-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Test Result Artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
      - name: Show Artifact Content
        run: ls
      - name: Deploy Artifact
        run: echo "Deploying..."
